const schema = [
  {
       "fieldName":"levelGroupAlias",
       "label":"等级组别名",
       "fieldType":"string",
       "modelType":"",
       "defaultValue":"",
       "modifiable":0,
       "previewable":0
   },
   {
       "fieldName":"type",
       "label":"会员模式",
       "fieldType":"number",
       "modelType":"",
       "defaultValue":1,
       "modifiable":0,
       "previewable":0
   },
   {
       "fieldName":"membershipIsMust",
       "label":"入会资料",
       "fieldType":"number",
       "modelType":"select",
       "defaultValue":true,
       "multiple":0,
       "modifiable":1,
       "previewable":1,
       "options":[
           {
               "label":"需要",
               "value":true
           },
           {
               "label":"不需要",
               "value":false,
               "next":{
                   "modelType":"select",
                   "children":[
                       "memberships"
                   ]
               }
           }
       ]
   },
   {
       "fieldName":"memberships",
       "label":"",
       "fieldType":"array",
       "modelType":"select",
       "defaultValue":[
           "手机号"
       ],
       "multiple":1,
       "modifiable":1,
       "previewable":1,
       "options":[
           {
               "label":"头像",
               "value":"头像"
           },
           {
               "label":"姓名",
               "value":"姓名"
           },
           {
               "label":"手机号",
               "value":"手机号",
               "modifiable":0
           },
           {
               "label":"性别",
               "value":"性别"
           },
           {
               "label":"生日",
               "value":"生日"
           },
           {
               "label":"地区",
               "value":"地区"
           }
       ]
   },
   {
       "fieldName":"level",
       "label":"",
       "fieldType":"object",
       "modelType":"group",
       "modifiable":0,
       "previewable":1,
       "fields":[
           {
               "fieldName":"groupSize",
               "label":"等级数量",
               "fieldType":"number",
               "modelType":"",
               "defaultValue":1,
               "modifiable":1,
               "previewable":1
           },
           {
               "fieldName":"levels",
               "label":"等级列表",
               "fieldType":"objectArray",
               "modelType":"table",
               "modifiable":1,
               "previewable":1,
               "fields":[
                   {
                       "fieldName":"",
                       "label":"",
                       "fieldType":"object",
                       "modelType":"",
                       "modifiable":0,
                       "previewable":0,
                       "fields":[
                           {
                               "fieldName":"levelAlias",
                               "label":"等级别名",
                               "fieldType":"string",
                               "modelType":"",
                               "defaultValue":"",
                               "modifiable":0,
                               "previewable":0
                           },
                           {
                               "fieldName":"name",
                               "label":"名称",
                               "fieldType":"string",
                               "modelType":"input",
                               "defaultValue":"黄金会员",
                               "modifiable":1,
                               "previewable":0
                           },
                           {
                               "fieldName":"minStoredValue",
                               "label":"升级条件",
                               "template":"单笔充{{minStoredValue}}元升级",
                               "fieldType":"number",
                               "modelType":"input",
                               "defaultValue":0,
                               "modifiable":1,
                               "previewable":0
                           },
                           {
                               "fieldName":"levelBenefit",
                               "label":"权益",
                               "fieldType":"object",
                               "modelType":"",
                               "modifiable":1,
                               "previewable":0,
                               "fields":[
                                   {
                                       "fieldName":"discount",
                                       "label":"折扣",
                                       "fieldType":"number",
                                       "modelType":"input",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0,
                                       "noLabel":"不打折",
                                       "noValue":0
                                   },
                                   {
                                       "fieldName":"pointsFeedBack",
                                       "label":"多倍积分",
                                       "fieldType":"number",
                                       "modelType":"input",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0
                                   },
                                   {
                                       "fieldName":"postageFree",
                                       "label":"运费",
                                       "fieldType":"boolean",
                                       "modelType":"select",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0,
                                       "multiple":0,
                                       "options":[
                                           {
                                               "label":"包邮",
                                               "value":"true"
                                           },
                                           {
                                               "label":"不包邮",
                                               "value":"false"
                                           }
                                       ]
                                   }
                               ]
                           },
                           {
                               "fieldName":"levelUpgradeGiftPack",
                               "label":"升级礼包",
                               "fieldType":"object",
                               "modelType":"",
                               "modifiable":1,
                               "previewable":0,
                               "fields":[
                                   {
                                       "fieldName":"points",
                                       "label":"积分",
                                       "fieldType":"number",
                                       "modelType":"input",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0
                                   },
                                   {
                                       "fieldName":"coupon",
                                       "label":"优惠券",
                                       "fieldType":"objectArray",
                                       "modelType":"",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0,
                                       "fields":[
                                           {
                                               "fieldName":"",
                                               "label":"",
                                               "fieldType":"object",
                                               "modelType":"",
                                               "modifiable":1,
                                               "previewable":0,
                                               "fields":[
                                                   {
                                                       "fieldName":"number",
                                                       "label":"赠送数量",
                                                       "fieldType":"number",
                                                       "modelType":"input",
                                                       "defaultValue":1,
                                                       "modifiable":1,
                                                       "previewable":0
                                                   },
                                                   {
                                                       "fieldName":"ids",
                                                       "label":"",
                                                       "fieldType":"array",
                                                       "modelType":"asyncSelect",
                                                       "scene":"goods",
                                                       "modifiable":1,
                                                       "defaultValue":[

                                                       ],
                                                       "previewable":0,
                                                       "apiId":"coupon",
                                                       "apiParams":[
                                                           {
                                                               "name":"keyWord",
                                                               "label":"关键字",
                                                               "type":"string"
                                                           }
                                                       ],
                                                       "pageInfoParams":[
                                                           {
                                                               "name":"pageNo",
                                                               "label":"分页页码",
                                                               "type":"number"
                                                           },
                                                           {
                                                               "name":"pageSize",
                                                               "label":"偏移量",
                                                               "type":"number"
                                                           }
                                                       ],
                                                       "globalParams":[
                                                           {
                                                               "name":"kdtId",
                                                               "label":"店铺ID",
                                                               "type":"number"
                                                           }
                                                       ],
                                                       "responseCovert":[
                                                           "id"
                                                       ]
                                                   }
                                               ]
                                           }
                                       ]
                                   },
                                   {
                                       "fieldName":"present",
                                       "label":"赠品",
                                       "fieldType":"objectArray",
                                       "modelType":"",
                                       "defaultValue":0,
                                       "modifiable":1,
                                       "previewable":0,
                                       "fields":[
                                           {
                                               "fieldName":"",
                                               "label":"",
                                               "fieldType":"object",
                                               "modelType":"",
                                               "modifiable":1,
                                               "previewable":0,
                                               "fields":[
                                                   {
                                                       "fieldName":"number",
                                                       "label":"赠送数量",
                                                       "fieldType":"number",
                                                       "modelType":"input",
                                                       "defaultValue":1,
                                                       "modifiable":1,
                                                       "previewable":0
                                                   },
                                                   {
                                                       "fieldName":"ids",
                                                       "label":"",
                                                       "fieldType":"array",
                                                       "modelType":"asyncSelect",
                                                       "scene":"goods",
                                                       "modifiable":1,
                                                       "defaultValue":[

                                                       ],
                                                       "previewable":0,
                                                       "apiId":"present",
                                                       "apiParams":[
                                                           {
                                                               "name":"keyWord",
                                                               "label":"关键字",
                                                               "type":"string"
                                                           }
                                                       ],
                                                       "pageInfoParams":[
                                                           {
                                                               "name":"pageNo",
                                                               "label":"分页页码",
                                                               "type":"number"
                                                           },
                                                           {
                                                               "name":"pageSize",
                                                               "label":"偏移量",
                                                               "type":"number"
                                                           }
                                                       ],
                                                       "globalParams":[
                                                           {
                                                               "name":"kdtId",
                                                               "label":"店铺ID",
                                                               "type":"number"
                                                           }
                                                       ],
                                                       "responseCovert":[
                                                           "id"
                                                       ]
                                                   }
                                               ]
                                           }
                                       ]
                                   }
                               ]
                           }
                       ]
                   }
               ]
           }
       ]
   }
];

export default schema;
